dist: xenial
language: node_js
node_js: node
cache: yarn
env:
  global:
  - secure: ydSeRiecN49Y2cimgdlvRRQjBOY7JF0THaThTFrq8kxDNHuohjX55Q2IT3PDpgwhwakRhLbOi6ub9R4GObshUUvV1gALh41j6n7JOd0hUIKwJN7dKg+IGprsHVeP8Oj+Mu19Oy9srYVnZJf7xLzgXjCqJZ1VBXlxZidISgtcHdbFyuxPc3tCGauI4Aq7HTH7yS5mjFtCnN/Hx8cjkntXtoKcRAiWuP4C8Vm8TIMfodHCPqPh1ZTAkUi3zdbvERS1z+Uyx4gH/GYJbvQ49OXNcKVNe+sFwhluPJhgIJMPiJiKI8d4jdzzOqOMYNHL3JcNoDBNuu3ZIPimykRTgfW7vdm8o1mYINbWZxr9NJx0S+inaqRXNRnuSOhF3S2YpdjpG+GSXA3wNlT3isN00mAZQDY264VPSbxPqxXeD7tAEh+BrKbIbO8E6QOpo92I1cLK92sYd7bK7IjWBnG3ZHom4yVKMlR0IJg/vjBCEgf0k1aB5JLIHCqzcuIiz5mbAAD9dC1c6d+dR1BlZTayjWG+DFJuwrmVUAh9BUbLrpMPh1d5rcKCAo3Px0KCOPgF+CLMO4kaGyh72iGCz53VNMRHRZt8PK9LtR96W7zHmCqNdYAjE3aMMHIIxUEDKHpfKHIzGgCrO++WsTIlCVjgD2/1TWNMMK8jouqOo+uqYGrU/GI=
  - secure: ml0tCi+hKNmiFcieP2dadFdbqyc0oDsrRP2Hwc4X/tGfYs5KFFTHN0JqPGhAd8vDqzJNOXuh2D4QyFat7UKC7GfWTQiRhI4gJX7RAytNXHlM9IrfAH+hsfwYks0GVvtvfzplDX50dHJJt/CiF+PU3D0NNMswE/9DwknAafOHPpAGfDqQsTPnWwm76OAY4EBZfGQwpGSCX+IgobuzA2Hfh2SnJpMJCZOAxNC4WIs4uLs+Kgv/mqvPCiN+aAoP5T92WLA4n2ZVZ9Vk3bZT0K3oG1Wh0KMv1Uf9AFXVQ4gtMghrldwFzK9g+IzG1JpQK/ksqAoGMzJBu5z1MRkDkbKNwuo5xpbzM0uYXDEDl0mGgB/FAaZEnfqX8Isx5leFzpPNBje6pgv+JjpfHRVW4olZ2IfDL6oUWJJsPT9hpaxp/FZlCwuikKjkDIsDpGs/2Tlphc+uXYF+bQCtbiOcFU5PGjO+EN0Gy9lAZBrlGhXsorOILE6UwOMs+CB3BMTWM6BfMLVuLoS6V283G8A6j5dw5pj8WR4yy/Iz4Gy4cYo8DtRlZmtIlEXG9sP3f474jP3r/pU2yXeLOPHzrsN/qJlwbu7nghFMKUQIrGjSYoDvISpgkaNPSkTi2ApUrBSORewxHNhk480KGghJFk1EQhWdAgd0XO1t0tBc3KA30FK+TA4=
branches:
  only:
    - master
deploy:
  provider: script
  skip_cleanup: true
  script:
  - yarn release
