name: CI
on:
  - push
  - pull_request
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: 13.x
    - uses: actions/cache@v1
      with:
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        path: ~/.cache/yarn
    - run: yarn
    - run: yarn test
    - run: yarn release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
